# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        formats:
            json: true
            html: true
            xml: true
            rss: false
        view_response_listener: force
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json, xml ] }
            - { path: '^/', fallback_format: html, prefer_extension: true, priorities: [ 'text/html', '*/*'] }
            
            